### ISSUE TITLE
Delete message or draft

### ISSUE THREAD

**Issue by sxbo672158** [nylas/nylas-python#1]
Following the example to define a namespace:
```
inbox = APIClient(APP_ID, APP_SECRET, token)

# Get the first namespace
namespace = inbox.namespaces.first()
```

I was not able to delete a message or draft by its id(error info attached)
```python
namespace.messages.delete('the message id I want to delete')
```
![image](https://cloud.githubusercontent.com/assets/1679034/4907448/077eba7c-6462-11e4-8ba1-7c6bcd17997b.png)

```python
namespace.drafts.delete('the draft id I want to delete')
```
![image](https://cloud.githubusercontent.com/assets/1679034/4907480/30169b30-6462-11e4-8661-156d35c834c0.png)

**Comment by brettgerry** [comment]
Fixed by https://github.com/nylas/nylas-python/commit/bf3bcb715f7a6f74849dd607bbe0fc86c2048207. Delete now supports passing request bodies and parameters. This also allows notify_participants to be sent as a parameter when deleting events.
