### ISSUE TITLE
Resources and Free/Busy support 

### ISSUE THREAD

**Issue by 2019342a** [nylas/nylas-python#136]
Hey Nylas Team!

Is support for the new resources and free/busy endpoints coming soon and if not,
do you accept PRs for that?

**Comment by BenLloydPearson** [comment]
Hello @2019342a, thanks for bringing this up. We will get these features implemented ASAP.

For what it's worth, we do accept PRs and you can learn about the process [here](https://github.com/nylas/nylas-python/blob/master/Contributing.md).

**Comment by 2019342a** [comment]
Ok! Thanks @BenLloydPearson for the update on that. I will close the issue then

**Comment by BenLloydPearson** [comment]
@2019342a We just released these features in version 4.10.0: https://pypi.org/project/nylas/4.10.0/

You can get this version by running `pip install --upgrade nylas`
