### ISSUE TITLE
Remove bumpversion as a runtime dependency?

### ISSUE THREAD

**Issue by samueldg** [nylas/nylas-python#144]
While installing `nylas`, I realized it also pulled the following:

```toml
bumpversion = ">=0.5.0"
six = ">=1.4.1"
urlobject = "*"
```

And indeed it's in the `setup.py`'s `install_requires`: https://github.com/nylas/nylas-python/blob/676547a3ba05dd6cc30322a9ed67575b540e0310/setup.py#L17

This was surprising to me, as this dependency is usually only for cutting new releases, but not actually required at runtime. Indeed, poking around a bit the only usage I see is:

https://github.com/nylas/nylas-python/blob/4a9200edab8321ef52235d061f140a0cd9545bbe/setup.py#L63

Could be worth using `extras_require` here, so maintainers can still install those dependencies easily: 

> `extras_require`
>
>    A dictionary mapping names of “extras” (optional features of your project) to strings or lists of strings specifying what other distributions must be installed to support those features. See the section below on Declaring Dependencies for details and examples of the format of this argument.

(See https://setuptools.readthedocs.io/en/latest/setuptools.html#new-and-changed-setup-keywords)

**Comment by mrashed-dev** [comment]
Thanks for the issue @samueldg, we are looking into this!

**Comment by mrashed-dev** [comment]
`bumpversion` is now no longer a runtime dependency, it has been moved to the `release` extra dependencies. To install the package needed for release, run `pip install nylas['release']`
