### ISSUE TITLE
Expose full response dict when calling POST `/oauth/token`

### ISSUE THREAD

**Issue by yi-fan-song** [nylas/nylas-python#189]
**Is your feature request related to a problem? Please describe.**

I don't ask for a user email on my end, so I need to get it from that response.

**Describe the solution you'd like**

Just another method that simply returns the response instead of the token.

```
def trade_code(self, code):
        args = {
            "client_id": self.client_id,
            "client_secret": self.client_secret,
            "grant_type": "authorization_code",
            "code": code,
        }

        headers = {
            "Content-type": "application/x-www-form-urlencoded",
            "Accept": "text/plain",
        }

        resp = requests.post(
            self.access_token_url, data=urlencode(args), headers=headers
        ).json()

        self.access_token = resp[u"access_token"]
        return resp
```

**Describe alternatives you've considered**

I'm making the call myself right now.

**Additional context**

**Comment by mrashed-dev** [comment]
@yi-fan-song thank you for opening this issue! We will investigate adding this to the SDK and let you know once it's been complete & released!

**Comment by mrashed-dev** [comment]
@yi-fan-song The fix has been merged into main and can be accessed via `send_authorization(code)`. It will be included in the next release coming very soon!

**Comment by mrashed-dev** [comment]
@yi-fan-song [Nylas Python SDK v5.5.0](https://github.com/nylas/nylas-python/releases/tag/v5.5.0) has been released containing this new function! Below is how you can access the full payload:

```python
from nylas import APIClient
nylas = APIClient(
    CLIENT_ID,
    CLIENT_SECRET,
    ACCESS_TOKEN
)

ACCESS_TOKEN = nylas.send_authorization('{code_from_nylas}')
```
