### ISSUE TITLE
Fetching Event and Updating Fails if Event was Not Created via Nylas API

### ISSUE THREAD

**Issue by jpulec** [nylas/nylas-python#219]
**Describe the bug**
It appears that when you fetch an event via the nylas api, and then perform any updates and try to save it, the nylas API rejects it if the event was not created via the Nylas API. This is because `conferencing` gets normalized on the event during `nylas.events.get()`, but causes `event.save()` to fail if the event was not created via the Nylas API.

**Comment by mrashed-dev** [comment]
@jpulec Thanks for opening this issue, we are taking a look into the issue and update you as soon as we have something to share.

**Comment by mrashed-dev** [comment]
@jpulec Thanks for your patience, the fix has been rolled out on the API side so no changes are required from your end. As long as you're not modifying any values in an Event's conferencing field that wasn't created by Nylas, you should not be getting an error anymore. If you are still experiencing issues please let me know!
