### ISSUE TITLE
The `collection.items` method does not obey the `offset` parameter

### ISSUE THREAD

**Issue by bengotow** [nylas/nylas-python#22]
From a discussion on the Community Slack channel. This function call:

```
client.threads.where(in_='inbox', limit=thread_size, offset=mail_offset).items()
```

Does not behave as expected. `items` ignores the provided offset and always returns starting with the 0th item. (https://github.com/nylas/nylas-python/blob/master/nylas/client/restful_model_collection.py#L22).

Alternatively, there's a method called `all`, but confusingly it obeys the preset offset but requires that you pass the limit as a parameter, ignoring the limit set in the where clause. This is also reported as not working as expected.

`client.threads.where(in_='inbox', offset=mail_offset).all(limit=thread_size)`

Ideally `items` and `all`would be merged together, and would obey the limit and offset provided in a where clause.

**Comment by pfista** [comment]
Fixed by https://github.com/nylas/nylas-python/commit/4deff685f5a61086b6525e666d104a78c979c107
