### ISSUE TITLE
Python SDK not working: 401 Unauthorized - invalid_request_error

### ISSUE THREAD

**Issue by hdotking** [nylas/nylas-python#242]
**Describe the bug**
Instantiating the APIClient object with `CLIENT_ID`, `CLIENT_SECRET` and `ACCESS_TOKEN` returns no error. But trying to use that instantiated object, you get a `401 Unauthorized error`.

**To Reproduce**
1. Sign up to the European version of Nylas and install `nylas` with pip
2. Get the three above mentioned credentials and instantiate the APIClient object to use the SDK as shown below).
```
from nylas import APIClient

CLIENT_ID = "xxxxxxxxx"
CLIENT_SECRET = "yyyyyyyyy"
ACCESS_TOKEN = "zzzzzzzz"

nylas = APIClient(CLIENT_ID, CLIENT_SECRET, ACCESS_TOKEN)
```
3. Run the code above. Get no error messages
4. Add the following line of code (or any code using the newly created  object `nylas`)
```
message = nylas.messages.first()
```
5. Get the error message below
```
Traceback (most recent call last):
  File "/Users/hdot/nylas/start_nylas.py", line 10, in <module>
    message = nylas.messages.first()
  File "/Users/hdot/.pyenv/versions/cloud-funcs/lib/python3.9/site-packages/nylas/client/restful_model_collection.py", line 56, in first
    results = self._get_model_collection(0, 1)
  File "/Users/hdot/.pyenv/versions/cloud-funcs/lib/python3.9/site-packages/nylas/client/restful_model_collection.py", line 154, in _get_model_collection
    return self.api._get_resources(self.model_class, **filters)
  File "/Users/hdot/.pyenv/versions/cloud-funcs/lib/python3.9/site-packages/nylas/client/client.py", line 568, in _get_resources
    results = _validate(response).json()
  File "/Users/hdot/.pyenv/versions/cloud-funcs/lib/python3.9/site-packages/nylas/client/client.py", line 72, in _validate
    raise NylasApiError(response)
nylas.client.errors.NylasApiError: 401 Unauthorized. Reason: Could not verify access credential.. Nylas Error Type: invalid_request_error
```

**Expected behavior**
See the correct response from calling the API (Not a 401 error).

**SDK Version:**
```
$pip freeze | grep nylas
nylas==5.11.0
```

**Additional context**
Tried refreshing the token but still no luck. The token itself works because all CURL commands in the playground/GUI work fine (no error messages and the correct output is shown).

**Comment by hdotking** [comment]
It turns out that the python SDK points to the USA `API_SERVER` url by default. Anyone working from Europe needs to change this URL manually...

This can be fixed by changing the [following line of code](https://github.com/nylas/nylas-python/blob/a1e3a73fa49c46d1acb4cbfcec6ee4fc282a36d2/nylas/client/client.py#L45) as shown below:

`API_SERVER = "https://api.nylas.com"` --> `API_SERVER = "https://ireland.api.nylas.com"`

This is quite restrictive for users in the EU as there doesn't appear to be a programmatic way to set this variable. It would be way better if we could pass the URL as an input argument to the `APIClient()` class. Possible feature request?

**Comment by mrashed-dev** [comment]
@hdotking thanks for opening (and closing) this issue! There is a way to set this variable without modifying the `API_SERVER` field! When initializing a new instance of APIClient you can pass in the Ireland domain as a setting:

```python
from nylas import APIClient

CLIENT_ID = "xxxxxxxxx"
CLIENT_SECRET = "yyyyyyyyy"
ACCESS_TOKEN = "zzzzzzzz"
EU_NYLAS_SERVER = "https://ireland.api.nylas.com"

nylas = APIClient(CLIENT_ID, CLIENT_SECRET, ACCESS_TOKEN, EU_NYLAS_SERVER)
```

Hope that helps! We are also looking to improve region selection in future updates of the SDK so that EU users don't have to manually set this domain.
