### ISSUE TITLE
Nylas Python doc

### ISSUE THREAD

**Issue by mingujo** [nylas/nylas-python#28]
On your website nylas.com, the python doc says, to fetch the threads, 
we have to initialize the accounts and look for threads on it. 
Like this:

```
account = client.accounts

# Fetch the first thread
thread = account.threads.first()

# Fetch a specific thread
thread = account.threads.find('ac123acd123ef123')
```

However, I believe the right way to look for a thread does not have to initialize 'accounts'.
Like this:

```
thread = client.threads.first()

thread = client.threads.find('blahblabblahbahb')

for thread in client.threads.items():
    #do whatever you want
```

Right? 

Otherwise, it gives me an error.

```
AttributeError: 'RestfulModelCollection' object has no attribute 'threads'
```

Thanks for the useful API!

**Comment by pfista** [comment]
The second way you described is the correct one! Thanks (/ 1 year late)
