### ISSUE TITLE
Request for Enhancement (RFE) - Add Support for Schedule Email Functionality

### ISSUE THREAD

**Issue by wiseaidev** [nylas/nylas-python#285]
### Problem Statement
[While building Code Inbox](https://devpost.com/software/code-inbox) and exploring the available features of Gmail, I discovered that Gmail supports schedule email, but it is not supported by this Nylas SDK. I would like to request the addition of a new feature to the Nylas SDK - support for scheduling emails.

![Screenshot from 2023-10-15 10-23-10](https://github.com/nylas/nylas-python/assets/62179149/9dde8c60-09ec-420d-802c-ecf8ab80f8f5)

### Proposed Solution
To add support for scheduling emails, I suggest implementing a feature that allows users to schedule the sending of emails at a specified date and time. This feature could be implemented using the `apscheduler` package, which supports scheduling tasks at specific dates and times.

## Context
The ability to schedule emails is a valuable feature for users who want to compose and send emails but choose to have them delivered at a later time. This can be particularly useful for time management, ensuring that emails are sent at an appropriate time for the recipient's time zone, or for composing emails in advance.

## Alternatives
As an alternative, users can resort to using third-party scheduling services or apps. However, having this functionality integrated into the Nylas SDK would provide a more seamless experience for users who rely on the SDK for their email-related tasks.

## References
- [Gmail API Documentation](https://developers.google.com/gmail/api/)
- [apscheduler Documentation](https://apscheduler.readthedocs.io/en/stable/)

## Impact
The addition of this feature would enhance the functionality of the Nylas SDK and make it more competitive and appealing to users who rely on scheduled email functionality.

## P.S.
Thank you for considering this feature request. I believe that adding support for scheduling emails would be a valuable addition to the Nylas SDK and would benefit many of its users.

**Comment by mrashed-dev** [comment]
Thanks for opening this ticket. I'm delighted to inform you that this feature is in the new Nylas API v3 and subsequently the new Nylas Python SDK v6. We currently have support for sending scheduled messages, as well as listing them and cancelling them.
