### ISSUE TITLE
Feat: Adding demo notebooks [Hacktoberfest]

### ISSUE THREAD

**Issue by mahimairaja** [nylas/nylas-python#301]
I could see the potential of the nylas python driver from various applications and integrations. However, it would be good to have some easy to start notebooks.

I would highly suggest the maintainer to add few `good first issues` in this `Hacktoberfest` season, So that the driver's full potential could be easily visible among the dev community. 

BTW, Thanks for the awesome work!

**Comment by relaxedtomato** [comment]
Hacktoberfest 2023 is complete - so closing this ticket for now 👍
