### ISSUE TITLE
Nylas v3.1.0 Features

### ISSUE THREAD

**Issue by JohnBurnsVC** [nylas/nylas-python#359]
Hello! I know Nylas v3.1.0 was just released very recently so I may be jumping the gun here -- But is there any timeline for when the new v3.1.0 features will be available here? Specifically I am looking to use the [cleaning email messages endpoint](https://developer.nylas.com/docs/api/v3/ecc/#put-/v3/grants/-grant_id-/messages/clean) via this package. For now I will use an external rest client but it would be awesome to have this functionality easily accessible here. Thanks for any intel, and for all the hard work keeping this repo in good shape!

**Comment by mamalovesyou** [comment]
Same here :) Would be nice to have it!

**Comment by mrashed-dev** [comment]
@JohnBurnsVC Hello! Sorry I didn't update this in time but we released v6.2.0 a week ago with these changes :) enjoy! https://github.com/nylas/nylas-python/releases/tag/v6.2.0.

cc @mamalovesyou
