### ISSUE TITLE
PyPI releases are not tracked as tags on github

### ISSUE THREAD

**Issue by mmautner** [nylas/nylas-python#7]
The [latest release](https://pypi.python.org/pypi/nylas) on PyPI (0.3) includes support for labels and folders, but the latest release tag on github is 0.2.4:

<img width="394" alt="screenshot 2015-07-29 16 06 47" src="https://cloud.githubusercontent.com/assets/1419652/8972136/d6340df6-360b-11e5-83b8-37809cbd0d3a.png">

Makes it hard to track releases

**Comment by jennielees** [comment]
Sorry about that, forgot to `git push --tags`. Updated the README as a reminder! :)
